---
title: "Santé humaine liée à l'obésité"
author: "Maëra Minique, Robert Dobbels, Arthur Baurain, Rohan Boulaki"
date: "`r Sys.Date()`"
format:
  html:
    code-fold: true
    code-tools: true
    toc: true
editor: visual
lang: fr
bibliography: bibliography/references.bib
---

<!--% Complétez l'entête en définissant un titre qui soit représentatif de votre travail. Indiquez aussi les noms des auteurs. -->

<!--# Dans les différentes sections, vous trouverez des indicateurs "...Vos XXX ici..." Vous devez bien sûr REMPLACER ces indicateurs par votre propre texte. Ne les laissez pas dans votre version finale du document. Vous devez travailler dans le même document (pas question de faire un document séparé par étudiant). Gérez les conflits éventuels. -->

```{r setup, include=FALSE}
# Ceci est nécessaire pour les tests SDD, ne pas utiliser dans un "vrai" projet
if (!"tools:tests" %in% search())
  source(here::here("tests/tools_tests.R"), attach(NULL, name = "tools:tests"))

# Configuration de l'environnement SciViews::R
SciViews::R("infer", lang = "fr")
```

# Introduction

<!--% Sur base de la bibliographie (lecture de l'article fourni et de vos propres recherches sur Internet), rédigez une introduction du sujet en 3 à 4 paragraphes. Cette introduction doit guider le lecteur vers votre but. Vous devez citer vos sources, c'est-à-dire qu’il faut indiquer au minimum la référence bibliographique fournie de manière correcte (inspirez-vous de ce qui est indiqué dans le bloc-notes, mais reformulez : un simple copier-coller de l'introduction du bloc-notes n'est PAS considéré comme l'exercice réalisé !) -->

<!--# Ce projet porte sur la santé humaine liée à l'obésité, à la façon de se nourrir et aux activités réalisées (plus ou moins sédentaire ou actif) ... Réalisez des recherches bibliographiques afin d'avoir une vision précise de la thématique. Existe-t-il des indicateurs calculables pour quantifier l'état de santé d'un individu, par exemple ? Naturellement, ces indicateurs doivent être calculables sur bases des variables mesurées dans votre jeu de données. Focalisez-vous donc sur ces variables-là. -->

Le surpoids et l'obésité sont définies comme une accumulation excessive de graisee corporelle. Une étude réalisée en Belgique en 2014 par l'OMS à montré que l'IMC moyen chez les adultes de 18 à 64 ans était de 26,3. Cela nous indique donc que, en belgique, les adultes sont en moyenne en surpoid. Comme nous le savons, certains facteurs influencent (fortement ou moins fortement) l'IMC (sexe, âge, alimentation, ...). L'analyse ne s'arrête pas en 2014. .En effet, le taux d'obésité en Belgique (et autres pays) a augmenté ces dernières décénnies.

Différents indices (IMC, RTH, tour de taille/taille, ...) existent pour tenter de quantifier le niveau de surpoids des individus. Dans notre projet, nous considérerons ces différents indices afin de déterminer tout d'abord si nos individus observés sont en situation de surpoids, de sous-poids ou en encore de poids "idéal".

Différents facteurs peuvent être à l'origine de cette augmentation du taux d'obésité dans notre pays. Comme nous l'indique l'université de Liège dans son article sur l'évolution de la consommation alimentaire en Belgique, la consommation de fast-food qui augmente au cours des années tout comme la consommation de viande jusque dans les années 80 tandis que la consommation de pomme de terre, de céréales et de lait diminue. Les consommations de fruits, de légumes et de sucre ont considérablement augmenté depuis 1980.

Les conséquentes d'un surpoids ou d'une obésité sont multiples sur la santé humaine. Selon l'OMS, une accumulation de graisse abdominale est associée à une augmentation de la pression artérielle et du risque d'hyperinsulinémie. Ce genre de problèmes peuvent mener à des maladies chroniques telles que le diabète de type 2 et les maladies cardiovasculaires. Ces soucis ne sont pas les seuls provoqués par une obésité, celle-ci peut également provoquer des troubles musculaires ou encore plus problématique, des cancers. Chez les individus jeunes (enfants), une obésité augmente le risque d'une mort prématurée et une possible limitation fonctionnelle lors de l'âge adulte.

# But

<!--% Formulez ici de façon concise et précise votre question de recherche en 1 à 2 phrases. -->

Cette étude porte à mesurer et comparer les différentes facteurs qui sont liée directement ou pas à l'obésité et si elles affectent ce problème positivement ou négativement.

# Matériel et méthodes

<!--% Cette section doit comprendre une explication technique sur les mesures effectuées et sur le protocole relatif à l'acquisition des données en 3 à 4 paragraphes. Vous ajouterez aussi un paragraphe qui détaille les outils logiciels et statistiques utilisés (logiciels et versions des logiciels). Un simple copier-coller du matériel et méthodes du bloc-notes ne sera PAS considéré comme acceptable. -->

#Les données ont été collectées par un groupe d'une trentaine d'expérimentateurs qui se sont réparti le travail. Le choix des mesures à réaliser a fait l'objet d'un consensus au sein du groupe par l'élaboration d'un dictionnaire des données commun. Les mesures sujettes à variation (la masse plus particulièrement) ont fait l'objet d'une intercalibration. Ces données sont pseudonymisées afin de respecter l'anonymat des sujets étudiés en respect du RGPD (règlement général de la protection des données, règlement d'application en Europe).#

Cette étude porte sur l'analyse de différentes variables liée ou pas à l'obésité, elle a été réalisé par un groupe d'une trentaines d'expérimentateurs qui ont interrogés et mesurer 144 personnes totales sur plusieurs variables. Pour les mesures de la masse, une intercalibration à été effectué au préalable, via l'utilisation d'une balance commune. Les mesures de taille etc... ont été considéré comme assez précise avec des instruments de mesure personelles. Le reste des mesures sont des simples questions posées aux individus

La description des données et les tests statistiques sont réalisés dans la SciViews Box 2024 en utilisant [Saturn Cloud](https://saturncloud.io) (Linux) avec le [logiciel R](https://www.r-project.org) (R version 4.3.0 (2023-04-21) \-- "Already Tomorrow").

# Résultats

## Description des données

<!--% Extrayez les quelques éléments les plus pertinents (3 à 5) de votre document `human_notebook.qmd` pour décrire les données de manière cohérente par rapport au but. Reprenez les interprétations en les reformulant de manière concise pour former un texte qui se lit en continu (donc un texte plus construit que ce que vous avez indiqué dans le bloc-notes). -->

<!--# N'oubliez pas que ce document doit pouvoir compiler indépendamment du reste. Cela implique que vous ajoutiez un chunk d'importation des données et que vous recalculiez tout ce qui doit l'être... Par contre, un simple copier-coller de toute la partie résultats du bloc-notes ne sera pas considéré comme un travail réalisé : vous devez sélectionner, et éventuellement remanier un peu le code, pour ne conserver que ce qui est utile ici. -->

...Vos descriptions des données ici...

## Tests d'hypothèses

<!--% Sélectionnez les 4 tests d'hypothèses les plus pertinents depuis `human_notebook.qmd`, ainsi bien sûr que les calculs des indices nécessaires que vous placerez juste au-dessus de vos tests. Ces tests doivent répondre à votre question de recherche (le but). Reformulez les interprétations pour former un texte qui se lit en continu. -->

...Vos tests d'hypothèses ici...

# Discussion et conclusions

<!--% Reprenez les résultats obtenus, discutez-les d'un point de vue biologique en 4 à 5 paragraphes et concluez votre travail. Vous pouvez les mettre également en relation avec vos recherches bibliographiques dans cette section. -->

...Vos conclusions ici...

<!--# Important : ce document doit compiler SANS ERREURS avec le bouton 'Rendu' sinon le travail sera sanctionné lourdement. La compilation du document Quarto est maintenant considérée comme acquise. -->

# Référence

<!--% N'indiquez rien ci-dessous. Quarto se chargera de rajouter vos références bibliographiques automatiquement. -->
